name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run skribos
      uses: leonidlezner/skribos-action@master
      with:
        build_dir: 'dist'
    - name: Deploy to Github Pages
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: dist
        keep_history: true
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
