name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Show info
      run: |
        echo ${GITHUB_REF:11}
    - name: Run Skribos
      uses: leonidlezner/skribos-action@master
      with:
        who-to-greet: 'Max'
      env:
        REF: ${{ GITHUB_REF:11 }}
